### PR TITLE
Create maven.yml

### PR DESCRIPTION
**Pull request by KangAgung**
mencoba mengimplementasikan CI di github

### CODE REVIEW

**Comment by KangAgung** [comment]
itu ada yang tau kenapa verify nya gagal ? @ivanetra @zakidevara

**Comment by ivanetra** [comment]
Belum ketemu issuenya di internet

**Comment by KangAgung** [comment]
urg edit dulu .yml nya

**Comment by ivanetra** [comment]
Oke

**Comment by KangAgung** [comment]
testing nya sih ok passed semua, cuman waktu verify nya ada issue seperti ini

`[ERROR] ---- Debugging information ----
[ERROR] message             : Cannot construct net.thucydides.core.reports.history.TestResultSnapshot as it does not have a no-args constructor
[ERROR] cause-exception     : com.thoughtworks.xstream.converters.reflection.ObjectAccessException
[ERROR] cause-message       : Cannot construct net.thucydides.core.reports.history.TestResultSnapshot as it does not have a no-args constructor
[ERROR] class               : net.thucydides.core.reports.history.TestResultSnapshot
[ERROR] required-type       : net.thucydides.core.reports.history.TestResultSnapshot
[ERROR] converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
[ERROR] path                : /net.thucydides.core.reports.history.TestResultSnapshot
[ERROR] line number         : 1
[ERROR] version             : null
[ERROR] -------------------------------`

**Comment by ivanetra** [comment]
Masih belum nemu issuenya

**Comment by KangAgung** [comment]
passed, tapi test nya ke skip

**Comment by KangAgung** [comment]
close dulu aja

**Pull request closed without merging**
